let DATA=[];
let PAPERS=JSON.parse(localStorage.getItem('scitech_papers')||'[]');
let ACTIVE=PAPERS.length?PAPERS[PAPERS.length-1]:null;
const COLORS={Physics:'#3b82f6',Chemistry:'#16a34a',Medicine:'#ef4444'};
const state={cats:{Physics:true,Chemistry:true,Medicine:true},start:1926,end:2025,scale:1,tx:0,ty:0,proxMode:'hybrid'};
const svg=document.getElementById('chart'),NS='http://www.w3.org/2000/svg';
const W=1100,H=720,M={top:52,right:40,bottom:72,left:78};
const X=v=>M.left+(v/100)*(W-M.left-M.right),Y=v=>H-M.bottom-(v/100)*(H-M.top-M.bottom);
const R=v=>6+((Math.sqrt(Math.max(40,v))-Math.sqrt(40))/(10-Math.sqrt(40)))*12;
const el=(tag,attrs={},text='')=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;return n};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function filtered(){return DATA.filter(d=>state.cats[d.category]&&d.year>=state.start&&d.year<=state.end)}
function tab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`))}
function render(){
 svg.innerHTML='';document.getElementById('count').textContent=filtered().length;document.getElementById('paperCount').textContent=PAPERS.length;
 const root=el('g',{transform:`translate(${state.tx} ${state.ty}) scale(${state.scale})`});svg.appendChild(root);
 const xm=X(50),ym=Y(50),rx=W-M.right;
 [[M.left,M.top,xm-M.left,ym-M.top,'#eef6ff'],[xm,M.top,rx-xm,ym-M.top,'#eefaf3'],[M.left,ym,xm-M.left,H-M.bottom-ym,'#faf7ef'],[xm,ym,rx-xm,H-M.bottom-ym,'#f7f3fb']].forEach(q=>root.appendChild(el('rect',{x:q[0],y:q[1],width:q[2],height:q[3],fill:q[4],stroke:'#fff'})));
 [['Applied Science + High Technology',25,96],['Fundamental Science + Transformative Technology',75,96],['Applied / Emerging',25,4],['Fundamental Science',75,4]].forEach(([t,x,y])=>root.appendChild(el('text',{x:X(x),y:Y(y),'text-anchor':'middle',class:'quad-label'},t)));
 for(let i=0;i<=100;i+=10){root.appendChild(el('line',{x1:X(i),y1:Y(0),x2:X(i),y2:Y(100),stroke:'#e6eaf0','stroke-width':.6}));root.appendChild(el('line',{x1:X(0),y1:Y(i),x2:X(100),y2:Y(i),stroke:'#e6eaf0','stroke-width':.6}));root.appendChild(el('text',{x:X(i),y:H-M.bottom+22,'text-anchor':'middle',class:'tick'},String(i)));root.appendChild(el('text',{x:M.left-12,y:Y(i)+4,'text-anchor':'end',class:'tick'},String(i)))}
 root.appendChild(el('text',{x:(M.left+rx)/2,y:H-18,'text-anchor':'middle',class:'axis-title'},'Scientific Fundamentalness →'));
 root.appendChild(el('text',{x:-(M.top+H-M.bottom)/2,y:24,'text-anchor':'middle',class:'axis-title',transform:'rotate(-90)'},'Demonstrated Technological Maturity →'));
 filtered().forEach(d=>{const g=el('g',{transform:`translate(${X(d.fundamentalScienceScore)} ${Y(d.technologyImpactScore)})`,class:'node'});const c=el('circle',{r:R(d.impactScore),fill:COLORS[d.category],'fill-opacity':.48,stroke:'#fff','stroke-width':2});c.onclick=e=>{e.stopPropagation();openNobel(d)};c.appendChild(el('title',{},`${d.year} · ${d.title}`));g.appendChild(c);g.appendChild(el('text',{x:R(d.impactScore)+4,y:4,class:'point-label'},`${d.year} ${d.title}`));root.appendChild(g)});
 PAPERS.forEach((p,idx)=>{const g=el('g',{transform:`translate(${X(p.fundamentalScienceScore)} ${Y(p.technologyMaturityScore)})`,class:'paper-node'});const size=ACTIVE===p?14:11;const poly=el('polygon',{points:`0,${-size} ${size},0 0,${size} ${-size},0`,fill:ACTIVE===p?'#5b21b6':'#8b5cf6',stroke:'#fff','stroke-width':2.4});poly.onclick=e=>{e.stopPropagation();ACTIVE=p;render();renderNobelProximity();openPaper(p)};poly.appendChild(el('title',{},`${p.title}\n${p.primaryArea}\nScience ${p.fundamentalScienceScore} · Tech ${p.technologyMaturityScore}`));g.appendChild(poly);g.appendChild(el('text',{x:16,y:4,class:'paper-label'},p.title||`Paper ${idx+1}`));root.appendChild(g)});
 renderPaperList();renderNobelProximity();
}
function setDrawer({header,title,people='',body='',science,tech,impact,why,tags=[]}){document.getElementById('backdrop').classList.remove('hidden');document.getElementById('drawerYear').textContent=header;document.getElementById('drawerTitle').textContent=title;document.getElementById('drawerLaureates').textContent=people;document.getElementById('drawerMotivation').textContent=body;document.getElementById('scoreScience').textContent=science;document.getElementById('scoreTech').textContent=tech;document.getElementById('scoreImpact').textContent=impact;document.getElementById('drawerExplanation').textContent=why;const box=document.getElementById('drawerTags');box.innerHTML='';tags.forEach(k=>{const s=document.createElement('span');s.textContent=k;box.appendChild(s)})}
function openNobel(d){setDrawer({header:`${d.year} · Nobel ${d.category}`,title:d.title,people:d.laureates.join(' · '),body:d.motivation,science:d.fundamentalScienceScore,tech:d.technologyImpactScore,impact:d.impactScore,why:d.explanation,tags:d.keywords})}
function openPaper(p){ACTIVE=p;renderNobelProximity();setDrawer({header:`LLM analysis · ${p.primaryArea}`,title:p.title||'Untitled paper',people:`Model: ${p.model||'unknown'} · Confidence: ${Math.round((p.confidence||0)*100)}%`,body:p.summary||'',science:p.fundamentalScienceScore,tech:p.technologyMaturityScore,impact:p.technologyPotentialScore,why:p.rationale,tags:[...(p.secondaryAreas||[]),...(p.signals||[])]})}
function renderPaperList(){const box=document.getElementById('paperList');box.innerHTML='';if(!PAPERS.length){box.innerHTML='<span class="muted">No papers yet.</span>';return}PAPERS.slice().reverse().forEach(p=>{const d=document.createElement('div');d.className='paper-item';d.innerHTML=`<strong>${esc(p.title||'Untitled paper')}</strong><span>${esc(p.primaryArea)} · X ${p.fundamentalScienceScore} · Y ${p.technologyMaturityScore}</span>`;d.onclick=()=>{ACTIVE=p;render();tab('nobel')};box.appendChild(d)})}
function proxValue(r){return state.proxMode==='conceptual'?r.conceptualScore:state.proxMode==='position'?r.positionScore:r.hybridScore}
function renderNobelProximity(){const box=document.getElementById('nobelProximityList');if(!ACTIVE||!ACTIVE.nobelProximity?.length){box.innerHTML='<span class="muted">Analyse or select a paper first.</span>';return}const rows=[...ACTIVE.nobelProximity].sort((a,b)=>proxValue(b)-proxValue(a)).slice(0,5);box.innerHTML='';rows.forEach((r,i)=>{const d=document.createElement('div');d.className='proximity-card';d.innerHTML=`<div class="prox-top"><strong>#${i+1} · ${r.year} ${esc(r.category)} · ${esc(r.title)}</strong><span class="prox-score">${Math.round(proxValue(r))}</span></div><div class="prox-meta">${esc((r.laureates||[]).join(' · '))}</div><div class="prox-bars"><span>Concept ${Math.round(r.conceptualScore)}</span><span>Map ${Math.round(r.positionScore)}</span><span>Hybrid ${Math.round(r.hybridScore)}</span></div>${r.rationale?`<div class="prox-rationale">${esc(r.rationale)}</div>`:''}`;d.onclick=()=>{const n=DATA.find(x=>x.id===r.id);if(n)openNobel(n)};box.appendChild(d)})}
async function checkModel(){try{const r=await fetch('/api/models');const j=await r.json();document.getElementById('modelName').textContent=j.selected||j.models?.[0]||'not configured';document.getElementById('analysisStatus').textContent=j.mode==='live'?'Spark LLM connected.':'Demo mode: Spark endpoint not reachable.';document.getElementById('analysisStatus').className='status '+(j.mode==='live'?'ok':'');const badge=document.getElementById('sparkBadge');badge.textContent=j.mode==='live'?`Spark · ${j.selected}`:'Spark demo';badge.className='badge '+(j.mode==='live'?'ok':'warn')}catch{document.getElementById('modelName').textContent='backend offline';document.getElementById('analysisStatus').textContent='Start server.py to enable analysis.'}}
async function analyze(){const abstract=document.getElementById('abstract').value.trim(),title=document.getElementById('paperTitle').value.trim();if(abstract.length<80){document.getElementById('analysisStatus').textContent='Please paste a longer abstract (at least 80 characters).';document.getElementById('analysisStatus').className='status error';return}const b=document.getElementById('analyzeBtn');b.disabled=true;b.textContent='Analysing…';document.getElementById('analysisStatus').textContent='Spark is positioning the paper and comparing Nobel references…';try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,abstract})});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Analysis failed');PAPERS.push(j);ACTIVE=j;localStorage.setItem('scitech_papers',JSON.stringify(PAPERS));showResult(j);render();tab('nobel');document.getElementById('analysisStatus').textContent=j.mode==='live'?'Analysed by Spark LLM.':'Analysed in demo heuristic mode.';document.getElementById('analysisStatus').className='status ok'}catch(e){document.getElementById('analysisStatus').textContent=e.message;document.getElementById('analysisStatus').className='status error'}finally{b.disabled=false;b.textContent='Analyse with Spark LLM'}}
function showResult(j){document.getElementById('paperResult').classList.remove('hidden');document.getElementById('resultArea').textContent=j.primaryArea;document.getElementById('resultScience').textContent=j.fundamentalScienceScore;document.getElementById('resultTech').textContent=j.technologyMaturityScore;document.getElementById('resultPotential').textContent=j.technologyPotentialScore;document.getElementById('resultConfidence').textContent=Math.round((j.confidence||0)*100)+'%';document.getElementById('resultRationale').textContent=j.rationale;document.getElementById('modelName').textContent=j.model||'unknown'}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));['Physics','Chemistry','Medicine'].forEach(cat=>document.getElementById('cat-'+cat).onchange=e=>{state.cats[cat]=e.target.checked;render()});document.getElementById('selectAll').onclick=()=>{Object.keys(state.cats).forEach(k=>{state.cats[k]=true;document.getElementById('cat-'+k).checked=true});render()};document.getElementById('clearAll').onclick=()=>{Object.keys(state.cats).forEach(k=>{state.cats[k]=false;document.getElementById('cat-'+k).checked=false});render()};const sy=document.getElementById('startYear'),ey=document.getElementById('endYear');sy.oninput=()=>{state.start=Math.min(+sy.value,state.end);sy.value=state.start;document.getElementById('startLabel').textContent=state.start;render()};ey.oninput=()=>{state.end=Math.max(+ey.value,state.start);ey.value=state.end;document.getElementById('endLabel').textContent=state.end;render()};document.getElementById('proximityMode').onchange=e=>{state.proxMode=e.target.value;renderNobelProximity()};document.getElementById('analyzeBtn').onclick=analyze;document.getElementById('clearPapers').onclick=()=>{PAPERS=[];ACTIVE=null;localStorage.removeItem('scitech_papers');document.getElementById('paperResult').classList.add('hidden');render()};document.getElementById('closeDrawer').onclick=()=>document.getElementById('backdrop').classList.add('hidden');document.getElementById('backdrop').onclick=e=>{if(e.target.id==='backdrop')e.currentTarget.classList.add('hidden')};let dragging=false,last={x:0,y:0};svg.addEventListener('wheel',e=>{e.preventDefault();const old=state.scale;state.scale=Math.max(.75,Math.min(6,state.scale*(e.deltaY<0?1.12:.89)));const rect=svg.getBoundingClientRect(),mx=(e.clientX-rect.left)/rect.width*W,my=(e.clientY-rect.top)/rect.height*H;state.tx=mx-(mx-state.tx)*(state.scale/old);state.ty=my-(my-state.ty)*(state.scale/old);render()},{passive:false});svg.onmousedown=e=>{dragging=true;last={x:e.clientX,y:e.clientY}};window.onmousemove=e=>{if(!dragging)return;state.tx+=(e.clientX-last.x)*(W/svg.clientWidth);state.ty+=(e.clientY-last.y)*(H/svg.clientHeight);last={x:e.clientX,y:e.clientY};render()};window.onmouseup=()=>dragging=false;svg.ondblclick=()=>{state.scale=1;state.tx=0;state.ty=0;render()}}
Promise.all([fetch('/api/nobels').then(r=>r.json())]).then(([d])=>{DATA=d;bind();render();checkModel()}).catch(e=>{console.error(e);document.getElementById('analysisStatus').textContent='Could not load Nobel dataset.'});
